%YAML:1.0

#--------------------------------------------------- lidar est path ----------------------------------------------------


lidar_est_path: "/home/mtcjyb/temp_ws/src/voxelOccupy/est/est_pose.txt"
          



#------------------------------------------------- 地图体素尺寸 path -------------------------------------------------- 
       
                 
dMaxMapVoxelSize: 0.1




#------------------------------------------------- 点云数据集的尺寸和 path -------------------------------------------------- 

seq_length: 37
dataset_folder: "/home/mtcjyb/my_test/dataset/ETHZ/local_frame_wood_summer/"


